import { writeFileSync } from "node:fs"
import type { SchemaDefinition } from "@ctroenv/core"
import { ExitCode } from "../exit-codes"
import { error, success } from "../utils/output"

interface DocsOptions {
  schema: SchemaDefinition
  output: string
  format: "markdown" | "json"
}

function formatType(typeLabel: string): string {
  return typeLabel
}

function generateMarkdown(schema: SchemaDefinition): string {
  const lines: string[] = []

  lines.push("# Environment Variables Reference")
  lines.push("")
  lines.push("*Generated by CtroEnv. Update schema, not this file.*")
  lines.push("")

  for (const [key, validator] of Object.entries(schema)) {
    const meta = validator.metadata

    lines.push(`## ${key}`)
    lines.push("")
    lines.push(`- **Type:** \`${formatType(meta.typeLabel)}\``)
    lines.push(`- **Required:** ${meta.optional ? "No" : "Yes"}`)

    if (meta.hasDefault) {
      lines.push(`- **Default:** \`${String(meta.defaultValue)}\``)
    }

    if (meta.description) {
      lines.push(`- **Description:** ${meta.description}`)
    }

    if (meta.isSecret) {
      lines.push("- **Sensitive:** Yes (masked in output)")
    }

    lines.push("")
  }

  return lines.join("\n")
}

function generateJson(schema: SchemaDefinition): string {
  const variables = Object.entries(schema).map(([key, validator]) => {
    const meta = validator.metadata
    return {
      key,
      type: meta.typeLabel,
      required: !meta.optional && !meta.hasDefault,
      description: meta.description ?? null,
      default: meta.hasDefault ? meta.defaultValue : null,
      isSecret: meta.isSecret,
    }
  })

  return JSON.stringify({ variables, count: variables.length }, null, 2)
}

export async function docsCommand(options: DocsOptions): Promise<number> {
  try {
    const content =
      options.format === "json" ? generateJson(options.schema) : generateMarkdown(options.schema)
    writeFileSync(options.output, content, "utf-8")
    process.stdout.write(`${success(`Generated ${options.output}`)}\n`)
    return ExitCode.Success
  } catch (e) {
    process.stdout.write(`${error(`Could not write ${options.output}:`)}\n`)
    console.error(e)
    return ExitCode.ConfigError
  }
}
