import { existsSync, mkdirSync, readFileSync, rmSync } from "node:fs"
import { resolve } from "node:path"
import { number, pick, string } from "@ctroenv/core"
import { describe, expect, it } from "vitest"
import { generateCommand } from "../commands/generate"
import { ExitCode } from "../exit-codes"

const TMP = resolve(__dirname, ".tmp-generate-test")

describe("generate command", () => {
  const schema = {
    DATABASE_URL: string().url().describe("Database connection URL"),
    PORT: number().port().default(3000).describe("Server port"),
    NODE_ENV: pick(["development", "production", "test"] as const).default("development"),
    JWT_SECRET: string().secret().describe("JWT signing secret"),
  }

  beforeEach(() => {
    rmSync(TMP, { recursive: true, force: true })
    mkdirSync(TMP, { recursive: true })
  })

  afterEach(() => {
    rmSync(TMP, { recursive: true, force: true })
  })

  it("generates .env.example with comments", async () => {
    const outputPath = resolve(TMP, ".env.example")
    const code = await generateCommand({
      schema,
      output: outputPath,
      noComments: false,
    })
    expect(code).toBe(ExitCode.Success)
    expect(existsSync(outputPath)).toBe(true)

    const content = readFileSync(outputPath, "utf-8")
    expect(content).toContain("DATABASE_URL")
    expect(content).toContain("PORT")
    expect(content).toContain("NODE_ENV")
    expect(content).toContain("JWT_SECRET")
    expect(content).toContain("Database connection URL")
    expect(content).toContain("Generated from schema")
  })

  it("generates minimal output with --no-comments", async () => {
    const outputPath = resolve(TMP, ".env.minimal")
    const code = await generateCommand({
      schema,
      output: outputPath,
      noComments: true,
    })
    expect(code).toBe(ExitCode.Success)

    const content = readFileSync(outputPath, "utf-8")
    expect(content).toContain("DATABASE_URL")
    expect(content).not.toContain("Generated by CtroEnv")
    expect(content).not.toContain("Database connection URL")
  })

  it("includes defaults for variables with defaults", async () => {
    const outputPath = resolve(TMP, ".env.example")
    await generateCommand({ schema, output: outputPath, noComments: false })
    const content = readFileSync(outputPath, "utf-8")
    expect(content).toContain("PORT=3000")
    expect(content).toContain("NODE_ENV=development")
  })

  it("comments out secret variables", async () => {
    const outputPath = resolve(TMP, ".env.example")
    await generateCommand({ schema, output: outputPath, noComments: false })
    const content = readFileSync(outputPath, "utf-8")
    expect(content).toContain("# JWT_SECRET=")
  })
})
